# Generated by Django 3.1.2 on 2020-10-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python', 'Python-3'), ('java', 'Java'), ('go', 'Go'), ('typescript', 'TypeScript')], max_length=20)),
                ('avaible', models.BooleanField(default=False)),
            ],
        ),
    ]
