# Generated by Django 3.1.2 on 2020-10-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='avaible',
            new_name='active',
        ),
    ]
