# Generated by Django 3.1.2 on 2020-10-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0005_auto_20201020_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python', 'Python'), ('java', 'Java'), ('go', 'Go'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript')], max_length=20, unique=True),
        ),
    ]
